/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/util/glb/m_2.glb 
*/

import React, { useEffect, useRef, useState } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';
import { useGraph } from '@react-three/fiber';

const Model = ({ defaultAnimation = "Run", ...props }) => {
  const { scene, animations } = useGLTF('/m_2.glb');
  const group = useRef();
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  const { actions } = useAnimations(animations, group);

  // `animation` 상태 변수 선언
  const [currentAnimation, setCurrentAnimation] = useState(defaultAnimation);

  useEffect(() => {
    // 모든 애니메이션을 중지시킨 후 새 애니메이션을 시작
    Object.values(actions).forEach((action) => {
      if (action) {
        action.stop();
      }
    });

    if (actions[currentAnimation]) {
      actions[currentAnimation].reset().fadeIn(0.5).play();
    } else {
      console.warn(`애니메이션 "${currentAnimation}"을 찾을 수 없습니다.`);
    }

    return () => {
      if (actions[currentAnimation]) {
        actions[currentAnimation].fadeOut(0.5).stop();
      }
    };
  }, [currentAnimation, actions]);


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig" position={[0, 0.018, 0]}>
          <group name="spine" position={[0, 0.775, -0.047]} rotation={[0.252, 0, 0]}>
            <group name="pelvisL" rotation={[-2.035, -0.82, -2.237]} />
            <group name="thighL" position={[0.098, 0.029, -0.001]} rotation={[2.774, 0, 0.005]}>
              <group name="shinL" position={[0, 0.319, 0]} rotation={[0.213, -0.001, -0.012]}>
                <group name="footL" position={[0, 0.421, 0]} rotation={[-1.342, -0.007, 0.001]}>
                  <group name="heel02L" position={[-0.032, -0.06, 0.097]} rotation={[2.815, 0, -Math.PI / 2]} />
                  <group name="toeL" position={[0, 0.161, 0]} rotation={[2.718, 0, -Math.PI]} />
                </group>
              </group>
            </group>
            <group name="spine001" position={[0, 0.13, 0]} rotation={[-0.181, 0, 0]}>
              <group name="spine002" position={[0, 0.201, 0]} rotation={[-0.103, 0, 0]}>
                <group name="spine003" position={[0, 0.147, 0]} rotation={[-0.004, 0, 0]}>
                  <group name="spine004" position={[0, 0.132, 0]} rotation={[0.277, 0, 0]}>
                    <group name="spine005" position={[0, 0.087, 0]} rotation={[-0.054, 0, 0]}>
                      <group name="spine006" position={[0, 0.053, 0]} rotation={[-0.188, 0, 0]} />
                    </group>
                  </group>
                  <group name="shoulderR" position={[-0.016, 0.088, 0.066]} rotation={[-1.536, 0.027, 0.968]}>
                    <group name="upper_armR" position={[-0.016, 0.178, -0.017]} rotation={[1.702, -1.009, 2.679]}>
                      <group name="forearmR" position={[0, 0.281, 0]} rotation={[0.255, -0.071, 0.127]}>
                        <group name="handR" position={[0, 0.245, 0]} rotation={[-0.034, 0.029, 0.038]}>
                          <group name="palm04R" position={[-0.001, 0.019, -0.038]} rotation={[0.241, -1.157, 0.676]}>
                            <group name="f_pinky01R" position={[0, 0.044, 0]} rotation={[0.054, 0.005, -0.074]}>
                              <group name="f_pinky02R" position={[0, 0.04, 0]} rotation={[0.195, -0.009, -0.114]} />
                            </group>
                          </group>
                          <group name="palm02R" position={[0.004, 0.027, 0.007]} rotation={[0.552, -1.317, 0.657]}>
                            <group name="f_middle01R" position={[0, 0.047, 0]} rotation={[0.127, 0.006, 0.038]}>
                              <group name="f_middle02R" position={[0, 0.056, 0]} rotation={[0.141, -0.006, -0.014]} />
                            </group>
                          </group>
                          <group name="palm01R" position={[0.004, 0.031, 0.03]} rotation={[0.759, -1.247, 0.737]}>
                            <group name="f_index01R" position={[0, 0.047, 0]} rotation={[0.014, -0.001, 0.03]}>
                              <group name="f_index02R" position={[0, 0.05, 0]} rotation={[0.125, 0.007, 0.038]} />
                            </group>
                            <group name="thumb01R" position={[0.015, 0, 0.016]} rotation={[-2.141, -0.976, -2.578]}>
                              <group name="thumb02R" position={[0, 0.053, 0]} rotation={[0.152, 0.006, 0.037]} />
                            </group>
                          </group>
                          <group name="palm03R" position={[0.003, 0.022, -0.016]} rotation={[0.166, -1.152, 0.487]}>
                            <group name="f_ring01R" position={[0, 0.044, 0]} rotation={[0.19, -0.004, -0.068]}>
                              <group name="f_ring02R" position={[0, 0.057, 0]} rotation={[0.08, -0.004, -0.061]} />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="shoulderL" position={[0.016, 0.088, 0.066]} rotation={[-1.536, -0.027, -0.968]}>
                    <group name="upper_armL" position={[0.016, 0.178, -0.017]} rotation={[1.702, 1.009, -2.679]}>
                      <group name="forearmL" position={[0, 0.281, 0]} rotation={[0.255, 0.071, -0.127]}>
                        <group name="handL" position={[0, 0.245, 0]} rotation={[-0.034, -0.029, -0.038]}>
                          <group name="palm01L" position={[-0.004, 0.031, 0.03]} rotation={[0.759, 1.247, -0.737]}>
                            <group name="f_index01L" position={[0, 0.047, 0]} rotation={[0.014, 0.001, -0.03]}>
                              <group name="f_index02L" position={[0, 0.05, 0]} rotation={[0.125, -0.007, -0.038]} />
                            </group>
                            <group name="thumb01L" position={[-0.015, 0, 0.016]} rotation={[-2.141, 0.976, 2.578]}>
                              <group name="thumb02L" position={[0, 0.053, 0]} rotation={[0.152, -0.006, -0.037]} />
                            </group>
                          </group>
                          <group name="palm03L" position={[-0.003, 0.022, -0.016]} rotation={[0.166, 1.152, -0.487]}>
                            <group name="f_ring01L" position={[0, 0.044, 0]} rotation={[0.19, 0.004, 0.068]}>
                              <group name="f_ring02L" position={[0, 0.057, 0]} rotation={[0.08, 0.004, 0.061]} />
                            </group>
                          </group>
                          <group name="palm02L" position={[-0.004, 0.027, 0.007]} rotation={[0.552, 1.317, -0.657]}>
                            <group name="f_middle01L" position={[0, 0.047, 0]} rotation={[0.127, -0.006, -0.038]}>
                              <group name="f_middle02L" position={[0, 0.056, 0]} rotation={[0.141, 0.006, 0.014]} />
                            </group>
                          </group>
                          <group name="palm04L" position={[0.001, 0.019, -0.038]} rotation={[0.241, 1.157, -0.676]}>
                            <group name="f_pinky01L" position={[0, 0.044, 0]} rotation={[0.054, -0.005, 0.074]}>
                              <group name="f_pinky02L" position={[0, 0.04, 0]} rotation={[0.195, 0.009, 0.114]} />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
            <group name="pelvisR" rotation={[-2.035, 0.82, 2.237]} />
            <group name="thighR" position={[-0.098, 0.029, -0.001]} rotation={[2.774, 0, -0.005]}>
              <group name="shinR" position={[0, 0.319, 0]} rotation={[0.213, 0.001, 0.012]}>
                <group name="footR" position={[0, 0.421, 0]} rotation={[-1.342, 0.007, -0.001]}>
                  <group name="heel02R" position={[0.032, -0.06, 0.097]} rotation={[2.815, 0, Math.PI / 2]} />
                  <group name="toeR" position={[0, 0.161, 0]} rotation={[2.718, 0, Math.PI]} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="rig">
          <primitive object={nodes['MCH-torsoparent']} />
          <primitive object={nodes.root} />
          <group name="m_2">
            <skinnedMesh name="Mesh029" geometry={nodes.Mesh029.geometry} material={materials.color} skeleton={nodes.Mesh029.skeleton} />
            <skinnedMesh name="Mesh029_1" geometry={nodes.Mesh029_1.geometry} material={materials.skin} skeleton={nodes.Mesh029_1.skeleton} />
            <skinnedMesh name="Mesh029_2" geometry={nodes.Mesh029_2.geometry} material={materials.color_spec} skeleton={nodes.Mesh029_2.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/m_2.glb')
export default Model